### PR TITLE
lazily import scipy to avoid import delay

### PR DESCRIPTION
**Pull request by drhodes**
Addresses #320

### CODE REVIEW

**Comment by jolyonb** [comment]
I did check how codejail interacts with scipy to make sure that scipy isn't being imported anyway; it's not.

**Comment by jolyonb** [comment]
Aww man, looks like codecov and travis have both broken :( Guess it's time to update the CV/CD pipeline!

**Comment by jolyonb** [comment]
@drhodes You'll be happy to know that all tests went through successfully on all versions of python :)

**Comment by jolyonb** [comment]
@drhodes I've created a new version/release/zipfile with this update. It should be ready to use immediately.

**Comment by drhodes** [comment]
@jolyonb, thank you so much for taking the time out to do this last night, I really appreciate it!

> I did check how codejail interacts with scipy to make sure that scipy isn't being imported anyway; it's not.

Good thinking on that! How unfortunate that would have been.

> ... codecov and travis have both broken :( Guess it's time to update the CV/CD pipeline!

I don't know anything about that stuff, but I really should. If you would like a hand with that, then please let me know. I'd like to start integrating automated checks with some other projects.

Thanks again!

**Pull request merged**
