### PR TITLE
Cleaning FormulaGrader and IntegralGrader

### PR DESCRIPTION
**Pull request by jolyonb**
This merges a bunch of the functionality of `FormulaGrader` and `IntegralGrader` into a mixin. This allows a bunch of `FormulaGrader` options to be incorporated into `IntegralGrader`. I'm going to write new tests and update documentation in a subsequent PR.

### CODE REVIEW

**Comment by jolyonb** [comment]
Most of this is just moving things around with a little generalization. Hopefully not too bad to review!

**Comment by ChristopherChudzicki** [comment]
Cool! Should be able to review tonight or Wednesday night at the latest.

**Comment by ChristopherChudzicki** [comment]
This all seems good. I've always been a bit wary of multiple inheritances, but this is definitely better than the copy pasta we had before.

Annoyingly codecov is not commenting on our PRs again, but the coverage report did run. There seem to be a few uncovered lines in integralgrader:

- coverage report: https://codecov.io/gh/mitodl/mitx-grading-library/commit/3040c2eff33d64e25f8f15b75b109b1f5f63a55e
- IntegralGrader coverage: https://codecov.io/gh/mitodl/mitx-grading-library/src/3040c2eff33d64e25f8f15b75b109b1f5f63a55e/mitxgraders/formulagrader/integralgrader.py

I guess we don't need to update the docs since IntegralGrader isn't documented at all...

Let me know what you want to do about the coverage. We've been sticklers about that in the past; not sure what you want to do now.

**Comment by jolyonb** [comment]
Thanks for taking the time to check this :-)

> This all seems good. I've always been a bit wary of multiple inheritances, but this is definitely better than the copy pasta we had before.

I don't think there's a better way to do it than multiple inheritance, given that `IntegralGrader` is not an `ItemGrader`. I could make the `MathMixin` class abstract, but I suspect that might invite more bugs than it's worth.

> Annoyingly codecov is not commenting on our PRs again, but the coverage report did run. There seem to be a few uncovered lines in integralgrader:
> 
>     * coverage report: https://codecov.io/gh/mitodl/mitx-grading-library/commit/3040c2eff33d64e25f8f15b75b109b1f5f63a55e
> 
>     * IntegralGrader coverage: https://codecov.io/gh/mitodl/mitx-grading-library/src/3040c2eff33d64e25f8f15b75b109b1f5f63a55e/mitxgraders/formulagrader/integralgrader.py
>
> I guess we don't need to update the docs since IntegralGrader isn't documented at all...

Ye of little faith! https://mitodl.github.io/mitx-grading-library/grading_math/integral_grader/

> Let me know what you want to do about the coverage. We've been sticklers about that in the past; not sure what you want to do now.

Given that this moved a lot of code around, I just wanted to have this as plain code. I'll make the next PR for tests and documentation updates.

**Comment by ChristopherChudzicki** [comment]
> Ye of little faith!

Indeed. My apologies 😄 .

Sounds good.

**Pull request merged**
