### PR TITLE
Version 1.2 documentation

### PR DESCRIPTION
**Pull request by ChristopherChudzicki**
- [x] documentation for `MatrixGrader`
    - course examples:
      - [x] basic example illustrating algebra, non-commutative behavior, error messages
      - [x] matrix entry-by-entry input example
      - [x] cross product example
      - [x] example highlighting vector vs single-row-matrix vs single-column-matrix
- [x] documentation for vector/matrix sampling classes
- [x] `specify_domain` documentation
    - [x] course example
- [x] document `comparer_function`s
    - [x] `NumericalGrader` course example using `is_between` comparer
    - [x] `MatrixGrader` course example using eigenvector/eigenvalue comparer
    - [x] `ListGrader` eigenvalue/eigenvector comparer demo
- [x] documentation for sibling variables when FormulaGrader used in ListGrader
    - [x]  course examples
- [x] consolidate `index.md` and `getting_starting.md` (there was a lot of overlap)

Some of these are very close to done.

[My version of the documentation website](https://christopherchudzicki.github.io/mitx-grading-library/)
[My version of demo course](https://edge.edx.org/courses/course-v1:CAC+CAC103+FOREVER/course/)

Note: I changed the theme to [mkdocs-cinder](https://github.com/chrissimpkins/cinder), because I wanted one level deeper on the individual page table of contents. Could explore other themes, but not going to worry about it now.

### CODE REVIEW

**Comment by jolyonb** [comment]
I'm sure this one is going to be huge -- we're catching up on two months' worth of features! I'm going to hold off on looking/making comments until you're done, I think.

I agree that focusing on some course demos for tomorrow's meeting(s?) is probably a good idea.

**Comment by jolyonb** [comment]
Can we make a standalone module of comparison functions, rather than having them scattered about randomly?

**Comment by ChristopherChudzicki** [comment]
> Can we make a standalone module of comparison functions, rather than having them scattered about randomly?

Sure! This was my original inclination, though MatrixGrader comparer_functions get a few extra `utils`.

**Comment by jolyonb** [comment]
I much prefer a standalone module. I think we should be able to figure out how to make something that works with the appropriate utils ;-) It can be exposed in a `comparers` module.

**Comment by ChristopherChudzicki** [comment]
@jolyonb Ready for review. My version of the demo course and website are update, see PR summary.

**Comment by ChristopherChudzicki** [comment]
rebased to fix merge conflicts

**Comment by jolyonb** [comment]
Thanks. I'm going to try to do the programmatic part of this tomorrow morning.

**Comment by jolyonb** [comment]
I'm merging this now, and will make updates in a future PR.

**Pull request merged**
