### PR TITLE
docs: bumpversion to 3.0.0

### PR DESCRIPTION
**Pull request by MaferMazu**
## Description

Bumpversion to 3.0.0

Related to #326

## Things to do

I will update the `python_lib.zip` file in this PR when we merge #329 and rebase this PR.

> [!NOTE]
> I tested with this [python_lib.zip](https://github.com/user-attachments/files/17781837/python_lib.zip) from #329

### CODE REVIEW

**Review by BryanttV — APPROVED** [review]
LGTM!

**Comment by MaferMazu** [comment]
With #329 merged, I updated the `python_lib.zip`.

I use this to generate it:
```bash
find mitxgraders voluptuous -type f ! -path "*/__pycache__/*" | zip python_lib.zip -@
```

**Comment by jolyonb** [comment]
If ever needed in the future, there's a script `makezip.sh` that builds the zip file :)

**Comment by jolyonb** [comment]
Ah... You forgot to put the license in the zip file. Can we please update?

**Pull request merged**
