### PR TITLE
process string even if some errors present

### LINKED ISSUE #117: MJxPrep needs better error handling
Consider the following typing:

```
                        // displays as:
cross(a,b) + fact       // a x b + fact
cross(a,b) + fact(      // cross(a,b) + fact(
cross(a,b) + fact(5     // cross(a,b) + fact(5
cross(a,b) + fact(5)    // a x b + 5!
```

errors in one part of a string should not prevent display of the rest.

I have a plan, but finishing column vector display first.

### PR DESCRIPTION
**Pull request by ChristopherChudzicki**
Resolves #117.

### CODE REVIEW

**Comment by jolyonb** [comment]
We also need to deal with `validateArgsLength`, which raises an error if there's an argument problem, rather than just saying "Skip this operation".

**Comment by ChristopherChudzicki** [comment]
> We also need to deal with validateArgsLength, which raises an error if there's an argument problem, rather than just saying "Skip this operation".

Good catch

**Comment by ChristopherChudzicki** [comment]
Should be good now.

**Comment by jolyonb** [comment]
Looks good. I'll merge once tests are done. Thanks for this!

**Pull request merged**
