### PR TITLE
Adding triangular matrix sampling

### PR DESCRIPTION
**Pull request by jolyonb**
This implements triangular matrix sampling, as described in #83. Documentation and tests included.

### CODE REVIEW

**Comment by ChristopherChudzicki** [comment]
Nice when we can make numpy do the work 😄 

Two questions:

First, are you thinking of
    - individual classes (Triangle, Orthogonal, Unitary...), or 
    - the generic version `SquareMatrixSampler` described in #83 with mixable keywords, or
    - both?

If both, will we need a lot of duplicate code? I haven't though too much about it.

Second: If separate classes, should `TriangularMatrices ` be real or complex? (Not really an issue if we make `SquareMatrixSampler` the main author-facing API.)

**Comment by jolyonb** [comment]
Well, triangular is special, because it doesn't just apply to square matrices. Also, unitary and orthogonal are also special, because you can't specify anything other than the dimension and determinant. Everything else can be covered by a `SquareMatrices` class, I think. However, this probably requires a little more thought as to how our matrix classes should be constructed... I'll make an issue.

**Comment by ChristopherChudzicki** [comment]
This still needs review and merge, right? Sorry it fell through the cracks, I was on vacation in March.

**Comment by jolyonb** [comment]
I think at this stage, this type of thing should be incorporated into the more general matrix sampling scheme that I outlined in #188. I've left this here for the moment though.

**Comment by jolyonb** [comment]
Closing this in favor of an upcoming PR.

**Pull request closed without merging**
